### ISSUE TITLE
Is is possible to annotate for research paper?

### ISSUE THREAD

**Issue by karpalig** [twighk/tghz-word-tone-annotator#18]
Is it possible manualy rewrite output style?

I would like to use this solution for citation in a scientific paper. I have inserted chinese characters in brackets after English translation and want to add pinyin before chinsee characters as given here:

![image](https://user-images.githubusercontent.com/7493374/112097342-cccc3b00-8bda-11eb-8eb2-a757ea7a32ec.png)

Chapter "Using'Chinese'Characters" in [Style&Guide&for&Essays&in&Chinese&Studies](https://www.ed.ac.uk/files/imports/fileManager/Style%20Guide%20for%20Essays%20in%20Chinese%20Studies.pdf)

Best, Alex

**Comment by karpalig** [comment]
basically

(真人) -> (_zhenren_ 真人)
or
真人 -> (_zhenren_ 真人)

**Comment by twighk** [comment]
Sorry, it's not possible to change the output style.

**Comment by twighk** [comment]
You could do it be editing the function:
`public static XElement withRuby(List<XAttribute> tattributes,List<XElement> tproperties, XNamespace w, string bottom, string topstr, int tone, bool topcolour = false, bool bottomcolour = false, List<string> colors = null)`
So that instead of building the XML for ruby text, it returns a text element.
